version: '2.3'
services:
  # To run benchmark suite docker-compose run --rm php src/benchmark
  php:
    image: prooph/php:7.4-cli
    environment:
      DRIVER: "postgres"
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "dev"
      POSTGRES_HOST: "database"
      POSTGRES_PORT: "5432"
      POSTGRES_CHARSET: "utf8"
      POSTGRES_DB: "event_store_tests"
    volumes:
      - "./:/app"
    #cpuset: phpcpuset
    #cpu_count: phpcpu_count
    #mem_limit: phpmem_limit
    #mem_reservation: phpmem_reservation

  database:
    image: postgres:12.3-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "event_store_tests"
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "dev"
    command: "-c 'max_connections=200'"
    #cpuset: dbcpuset
    #cpu_count: dbcpu_count
    #mem_limit: dbmem_limit
    #mem_reservation: dbmem_reservation
