version: '2.3'
services:
  # To run benchmark suite docker-compose run --rm php src/benchmark
  php:
    image: vpack72
    build:
      context: ./env
      dockerfile: Dockerfile
    environment:
      USE_VPACK: "true"
      DRIVER: "arangodb"
      PHP_IDE_CONFIG: "serverName=application"
      ARANGODB_HOST: "tcp://database:8529"
      ARANGODB_USERNAME: ""
      ARANGODB_PASSWORD: ""
      ARANGODB_DB: event-store-bench
    volumes:
      - "./:/app"
    #cpuset: phpcpuset
    #cpu_count: phpcpu_count
    #mem_limit: phpmem_limit
    #mem_reservation: phpmem_reservation

  database:
    image: arangodb/arangodb-preview:devel
    ports:
      - 8529:8529
    environment:
      ARANGO_NO_AUTH: 1
    #cpuset: dbcpuset
    #cpu_count: dbcpu_count
    #mem_limit: dbmem_limit
    #mem_reservation: dbmem_reservation
