version: '2.3'
services:
  # To run benchmark suite docker-compose run --rm php src/benchmark
  php:
    image: prooph/php:7.2-cli
    environment:
      DRIVER: "mysql"
      MYSQL_USER: "dev"
      MYSQL_PASSWORD: "dev"
      MYSQL_HOST: "database"
      MYSQL_PORT: "3306"
      MYSQL_CHARSET: "utf8"
      MYSQL_DB: "event_store_tests"
    volumes:
      - "./:/app"
    #cpuset: phpcpuset
    #cpu_count: phpcpu_count
    #mem_limit: phpmem_limit
    #mem_reservation: phpmem_reservation

  database:
    # mysql 8.0 not working properly
    # see https://github.com/docker-library/mysql/issues/303
    #image: mysql:8.0.13
    image: mysql:5.7.24
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "event_store_tests"
      MYSQL_USER: "dev"
      MYSQL_PASSWORD: "dev"
    volumes:
      - "./env/mysql:/etc/mysql/conf.d:ro"
    command: "--innodb_buffer_pool_size=BUFFER_POOL_SIZE"
    #cpuset: dbcpuset
    #cpu_count: dbcpu_count
    #mem_limit: dbmem_limit
    #mem_reservation: dbmem_reservation
